language: java

jdk:
  - oraclejdk8
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mvn verify -B -V
  
after_script: 
  - ./cc-test-reporter format-coverage -d -t jacoco
  - ./cc-test-reporter upload-coverage -d
 



